config/routes.rb
BlogEngine::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'articles#index'
  resources :articles
end

app/models/blog_engine/article.rb
module BlogEngine
  class Article < ActiveRecord::Base
    validates :title, presence: true
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/blog_engine/application_controller.rb
module BlogEngine
  class ApplicationController < ActionController::Base
  end
end

app/controllers/blog_engine/articles_controller.rb
require_dependency "blog_engine/application_controller"

module BlogEngine
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    # GET /articles
    def index
      @articles = Article.all
    end

    # GET /articles/1
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        redirect_to @article, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def article_params
        params.require(:article).permit(:title, :body)
      end
  end
end

app/helpers/blog_engine/application_helper.rb
module BlogEngine
  module ApplicationHelper
  end
end

app/helpers/blog_engine/articles_helper.rb
module BlogEngine
  module ArticlesHelper
  end
end

app/views/blog_engine/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <br>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'ckeditor' %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/blog_engine/articles/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('blog_engine.show'), @article %> |
<%= link_to t('blog_engine.back'), articles_path %>

app/views/blog_engine/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t '.title' %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= BlogEngine::Article.human_attribute_name("title") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td>

          <%= link_to article do %>
            <span class="glyphicon glyphicon-eye-open"></span>
            <%= t 'blog_engine.show' %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_article_path(article) do %>
            <span class="glyphicon glyphicon-edit"></span>
            <%= t 'blog_engine.edit' %>
          <% end %>
        </td>
        <td>
          <%= link_to article, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
            <%= t 'blog_engine.delete' %>
          <% end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_article_path do %>
  <span class="glyphicon glyphicon-plus"></span>
  <%= t 'blog_engine.new' %>
<% end %>

app/views/blog_engine/articles/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('blog_engine.back'), articles_path %>

app/views/blog_engine/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @article.title %></h1>
<p>
  <%= sanitize @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<button class="btn btn-primary">test</button>

app/views/layouts/blog_engine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogEngine</title>
  <!-- Latest compiled and minified CSS -->
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
  <%= stylesheet_link_tag    "blog_engine/application", media: "all" %>
  <%= javascript_include_tag "blog_engine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>